esphome:
  name: espgoveestrip

esp32:
  board: lolin32_lite

logger:

interval:
  - interval: 1min
    then:
      - logger.log: "timer event"
      - light.turn_off:
          id: strip
      - delay: 5s
      - light.turn_on:
          id: strip
          effect: "Random Colors"

light:
  - platform: esp32_rmt_led_strip
    rmt_channel: 0
    chipset: ws2812
    id: strip
    pin: GPIO14
    num_leds: 20
    rgb_order: GRB
    name: "Govee RGB Strip"
    default_transition_length: 500ms

    effects:      
      - addressable_lambda:
          name: "Random Colors"
          update_interval: 2000ms
          lambda: |-
            for (int i = 0; i < it.size(); i++) {
              it[i] = ESPColor::random_color().darken(150);
            }

